### ISSUE TITLE
Unable to run apex-ast-serializer-http

### ISSUE THREAD

**Issue by arosenbach** [dangmai/apex-ast-serializer#52]
Since c26775ec17a0604be9abe34cd9d14fb38f1d7cd5, `apex-ast-serializer-http` fails to run (Java 8):
```bash
$ bin/apex-ast-serializer-http
Unrecognized option: --add-opens=java.base/java.lang=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
$ java -version                                                                                                                
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.10-SA-macosx) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.10-SA-macosx) (build 25.212-b04, mixed mode)
```

Note: this bug also breaks `prettier-plugin-apex` (1.9.0)

**Comment by dangmai** [comment]
Hi, thank you for the bug report. This is the intended behavior, I'm no longer supporting JDK8 for this project, as you can see in the CHANGELOG [here](https://github.com/dangmai/prettier-plugin-apex/releases/tag/v1.9.0). Supporting Java 8 and 16 simultaneously is not simple, because the reflection access that's used for the AST serialization is pretty different from each other, and I don't want to accrue that tech debt in order to support Java 8 which no longer receives public update.

My suggestion is to use AdoptOpenJDK 11 or above.
